### ISSUE TITLE
README translations

### ISSUE THREAD

**Issue by matteobruni** [matteobruni/object-gui#34]
A translated README could help users understand better what this library does and how to use it.

I can contribute to English and Italian, any other language is welcome

**Comment by lancaluis** [comment]
Hey! Can I help with this issue?

**Comment by Chemasmas** [comment]
@matteobruni Can I help with the ES-MX version?

**Comment by matteobruni** [comment]
Hi @lancaluis and @Chemasmas,

Yes you can both contribute

**Comment by flitzmare** [comment]
I can help translating into id-ID :)

**Comment by TomerPacific** [comment]
@matteobruni , I can help translate the README.md file to Hebrew (he-il).

**Comment by matteobruni** [comment]
@TomerPacific yes, feel free to contribute
