### ISSUE TITLE
Typo in package.json?

### ISSUE THREAD

**Issue by godric3** [matteobruni/object-gui#60]
For me it looks like a typo:
 In keywords in [package.json](https://github.com/matteobruni/object-gui/blob/master/package.json#L9) there is `wyiswyg` instead of `wysiwyg`. Looks like this is the case also for  [tsparticles-editor](https://github.com/matteobruni/tsparticles/blob/master/core/editor/package.json#L12)

Also I see that in package.json license is set to `ISC` while in repo file LICENSE contains `MIT` license, is it intended?

**Comment by matteobruni** [comment]
Thanks, I never noticed that. It’s definitely a typo
